name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make server
