name: Test

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Download and verify modules
        run: |
          make dep
      - name: Test
        run: |
          make test
          make race
